DROP TABLE IF EXISTS BC_CERT_CFG_DETAIL;
DROP TABLE IF EXISTS BC_CERT_CFG;
DROP TABLE IF EXISTS BC_CERT_TYPE;


CREATE TABLE BC_CERT_TYPE (
  ID INT NOT NULL,
  CODE VARCHAR(100) NOT NULL UNIQUE,
  NAME VARCHAR(255) NOT NULL,
  ORDER_NO VARCHAR(10),
  AUTHOR_ID INT NOT NULL,
  FILE_DATE TIMESTAMP NOT NULL,
  MODIFIER_ID INT NOT NULL,
  MODIFIED_DATE TIMESTAMP NOT NULL,
  CONSTRAINT BCPK_CERT_TYPE PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_CERT_TYPE IS '证件类别';
COMMENT ON COLUMN BC_CERT_TYPE.ID IS 'ID';
COMMENT ON COLUMN BC_CERT_TYPE.CODE IS '编码';
COMMENT ON COLUMN BC_CERT_TYPE.NAME IS '名称';
COMMENT ON COLUMN BC_CERT_TYPE.ORDER_NO IS '排序号';
COMMENT ON COLUMN BC_CERT_TYPE.AUTHOR_ID IS '创建人ID';
COMMENT ON COLUMN BC_CERT_TYPE.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BC_CERT_TYPE.MODIFIER_ID IS '最后修改人ID';
COMMENT ON COLUMN BC_CERT_TYPE.MODIFIED_DATE IS '最后修改时间';
ALTER TABLE BC_CERT_TYPE
  ADD CONSTRAINT BCFK_CERT_TYPE_AUTHOR FOREIGN KEY (AUTHOR_ID)
  REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID)
  ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BC_CERT_TYPE
  ADD CONSTRAINT BCFK_CERT_TYPE_MODIFIER FOREIGN KEY (MODIFIER_ID)
  REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID)
  ON UPDATE RESTRICT ON DELETE RESTRICT;


CREATE TABLE BC_CERT_CFG (
  ID INT NOT NULL,
  UID_ VARCHAR(36) NOT NULL,
  STATUS_ INT NOT NULL,
  TYPE_ID INT NOT NULL,
  CODE VARCHAR(100) NOT NULL UNIQUE,
  NAME VARCHAR(100) NOT NULL,
  PAGE_COUNT INT NOT NULL,
  WIDTH DECIMAL(10,2) NOT NULL,
  COMBINE VARCHAR(50),
  ORDER_NO VARCHAR(10),
  TPL VARCHAR(100) NOT NULL,
  AUTHOR_ID INT NOT NULL,
  FILE_DATE TIMESTAMP NOT NULL,
  MODIFIER_ID INT NOT NULL,
  MODIFIED_DATE TIMESTAMP NOT NULL,
  ONE_PAGE_ONE_TYPOGRAPHY INT NOT NULL,
  PRINT_DIRECTION int NOT NULL,
  CONSTRAINT BCPK_CERT_CFG PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_CERT_CFG IS '证件配置';
COMMENT ON COLUMN BC_CERT_CFG.ID IS 'ID';
COMMENT ON COLUMN BC_CERT_CFG.UID_ IS 'UID_';
COMMENT ON COLUMN BC_CERT_CFG.STATUS_ IS '状态 : 0-正常,1-禁用';
COMMENT ON COLUMN BC_CERT_CFG.TYPE_ID IS '所属类别ID';
COMMENT ON COLUMN BC_CERT_CFG.CODE IS '编码';
COMMENT ON COLUMN BC_CERT_CFG.NAME IS '名称';
COMMENT ON COLUMN BC_CERT_CFG.PAGE_COUNT IS '面数';
COMMENT ON COLUMN BC_CERT_CFG.WIDTH IS '打印宽度 : 毫米单位';
COMMENT ON COLUMN BC_CERT_CFG.COMBINE IS '合并配置';
COMMENT ON COLUMN BC_CERT_CFG.ORDER_NO IS '排序号';
COMMENT ON COLUMN BC_CERT_CFG.TPL IS '所用模板';
COMMENT ON COLUMN BC_CERT_CFG.AUTHOR_ID IS '创建人';
COMMENT ON COLUMN BC_CERT_CFG.FILE_DATE IS '创建时间';
COMMENT ON COLUMN BC_CERT_CFG.MODIFIER_ID IS '最后修改人';
COMMENT ON COLUMN BC_CERT_CFG.MODIFIED_DATE IS '最后修改时间';
COMMENT ON COLUMN BC_CERT_CFG.ONE_PAGE_ONE_TYPOGRAPHY IS '一页一版';
COMMENT ON COLUMN BC_CERT_CFG.PRINT_DIRECTION IS '打印方向，默认是0，纵向打印';
ALTER TABLE BC_CERT_CFG
  ADD CONSTRAINT BCFK_CERT_CFG_TYPE FOREIGN KEY (TYPE_ID)
  REFERENCES BC_CERT_TYPE (ID)
  ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BC_CERT_CFG
  ADD CONSTRAINT BCFK_CERT_CFG_AUTHOR FOREIGN KEY (AUTHOR_ID)
  REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID)
  ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE BC_CERT_CFG
  ADD CONSTRAINT BCFK_CERT_CFG_MODIFIER FOREIGN KEY (MODIFIER_ID)
  REFERENCES BC_IDENTITY_ACTOR_HISTORY (ID)
  ON UPDATE RESTRICT ON DELETE RESTRICT;


CREATE TABLE BC_CERT_CFG_DETAIL (
  ID INT NOT NULL,
  PID INT NOT NULL,
  PAGE_NO INT NOT NULL,
  WIDTH DECIMAL(10,2) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  CONSTRAINT BCPK_CERT_CFG_DETAIL PRIMARY KEY (ID)
);
COMMENT ON TABLE BC_CERT_CFG_DETAIL IS '证件配置明细';
COMMENT ON COLUMN BC_CERT_CFG_DETAIL.ID IS 'ID';
COMMENT ON COLUMN BC_CERT_CFG_DETAIL.PID IS '所属配置ID';
COMMENT ON COLUMN BC_CERT_CFG_DETAIL.PAGE_NO IS '页码';
COMMENT ON COLUMN BC_CERT_CFG_DETAIL.WIDTH IS '打印宽度 : 毫米单位';
COMMENT ON COLUMN BC_CERT_CFG_DETAIL.NAME IS '名称';

ALTER TABLE BC_CERT_CFG_DETAIL
  ADD CONSTRAINT BCFK_CERT_CFG_DETAIL FOREIGN KEY (PID)
  REFERENCES BC_CERT_CFG (ID)
  ON UPDATE RESTRICT ON DELETE CASCADE;
